App\Entity\Book:
  attributes:
    id:
      groups: ["book"]
    title:
      groups: ["book"]
    description:
      groups: ["book"]
    score:
      groups: ["book"]
    image:
      groups: ["book"]
    categories:
      groups: ["book"]  
